### ISSUE TITLE
what is the output of the model from MC ?

### ISSUE THREAD

**Issue by Siziff** [csbhr/FFHQ-UV#11]
It is not possible to run the model because there is no account on Azure. What is the output of the detect_face function in your project? Are there any similar open libraries for solving this problem without using the api?

**Comment by csbhr** [comment]
The goal of Azure Face Api is to detect some attributes (Age, Baldness, Beard, Expression, Gender, Glasses, Pitch, Yaw) of inverted faces, and then output a '.json' file like [this file](https://github.com/csbhr/FFHQ-UV/blob/main/examples/dataset_examples/attributes/01223.json)

You also can use other detectors to detect these attributes.

Recently I am occupied by other things, in the near future, we will provide project details of the FFHQ-UV dataset creation pipeline, including inversion latents/faces, detected face attributes, sample correspondence, etc.

**Comment by csbhr** [comment]
The project details of the FFHQ-UV dataset creation pipeline are available [[here]](https://github.com/csbhr/FFHQ-UV/blob/main/README_dataset.md#ffhq-uv-dataset-project-details), including inverted faces' latent codes (latents.zip) and detected face attributes of inverted faces (lights.zip, attributes.zip, attributes_ms_api.zip).

With these files, one can directly run step3 (DataSet_Step3_Editing) and step4 (DataSet_Step4_UV_Texture) to generate final texture UV-maps.

In "attributes_ms_api.zip", we provide the object returned by MS Face API, where one can find other detected attributes (e.g., age, gender, headPose, smile, facialHair, glasses, emotion, hair, makeup, occlusion, accessories, blur, exposure, noise, qualityForRecognition).

Since 380 samples failed in the [encoder4editing](https://github.com/omertov/encoder4editing) inversion task, we only provide information of the remaining 69620 samples.
