### ISSUE TITLE
How to improve shape optimization 

### ISSUE THREAD

**Issue by ujjawalcse** [csbhr/FFHQ-UV#12]
Hey @csbhr ,
Thanks a lot for releasing the code. I tried the given run_rgb_fitting.sh and it's working fine.
But output face shape is not matching with the input as it's giving round faces in most of the cases.

Any idea how to improve the shape optimization part running in step 3 of ours_fit_model.py module?

Reference input,
![Ranbir_Kapoor_promoting_Brahmastra_1676026251_2033703](https://user-images.githubusercontent.com/32773256/218999096-3c3e1c98-3ded-4cd7-9ca3-e071d1bd034b.jpg)

Reference output,
![ranvir](https://user-images.githubusercontent.com/32773256/218999653-3adccaa8-14e2-4385-87a5-401cd33dc041.png)

**Comment by csbhr** [comment]
From the pre-processing results in the figure below, the face parsing does not exclude the hand area. The fitting process would be affected by the hand texture. More accurate face parsing results might helpful.

![issue13](https://user-images.githubusercontent.com/26042636/220925237-c83350cd-1863-4975-a04e-ce085090f2e7.png)

**Comment by ujjawalcse** [comment]
@csbhr , This is a case of occlusion. But I have tested with other clear images too. 
Normally, It's coming more round like 3D shapes.
Check this reference input and corresponding output,
![Pic_1676008638_7974665](https://user-images.githubusercontent.com/32773256/221112039-89302393-e321-4806-9d60-7ba2cdce5b12.jpg)

![saurav](https://user-images.githubusercontent.com/32773256/221112475-9d786634-1c46-47e3-9f86-21c2f16e22e7.png)
![stage3_vis](https://user-images.githubusercontent.com/32773256/221112592-54c1dea3-0692-4b29-8dd6-5d5f343ba75d.png)

**Comment by csbhr** [comment]
<img width="508" alt="image" src="https://user-images.githubusercontent.com/26042636/221113784-deb2763f-fcbd-4c81-88b4-b2fcab69c58b.png">

From the 68 landmarks in the image above (gt landmarks in blue and fitted landmarks in red), it can be seen that the landmarks at the bottom of the face are not well fitted. This may be caused by the weight used in landmark loss (see the image below, or [the source codes](https://github.com/csbhr/FFHQ-UV/blob/main/RGB_Fitting/model/losses.py#L68)).

On Line79-Line81, we weighted the landmarks of nose and mouth more heavily.
Perhaps, setting the weight of all landmarks to **1** is helpful for fitting the bottom contour of the face.

<img width="611" alt="image" src="https://user-images.githubusercontent.com/26042636/221114728-2022ed7b-9380-497c-ac0c-dfffa1cfe5ef.png">

**Comment by ujjawalcse** [comment]
@csbhr Tried what you suggested and now the outer shapes are better. But on the cost of a slightly less optimised mouth and nose area. We can't even observe those if we see them separately. We can notice those gaps after overlapping the previous result with the new result.
For now, I tried with assigning all landmarks weights as 1.
 I'll try with lesser weight for mouth and nose instead of 20. It may be a better trade-off.  
Thanks @csbhr.

**Comment by csbhr** [comment]
Thank you for sharing your experiments. Hope our codes are useful to you.

**Comment by pyh007** [comment]
如何用更轻的口鼻
