### ISSUE TITLE
Microsoft Face API不能使用

### ISSUE THREAD

**Issue by ZPzhu** [csbhr/FFHQ-UV#19]
你好，请问[Microsoft Face API]不能使用，有没有替代方案呢？

**Comment by ZPzhu** [comment]
![image](https://user-images.githubusercontent.com/51941034/222952832-80c305c9-9220-4dab-a34c-1bf38756e5c9.png)
或者能否提供一下ffhq数据集生成后的这些文件

**Comment by csbhr** [comment]
最近忙于其他事情，近期我们会公布数据集的中间结果（inversion latents/faces, detected face attributes）。

**Comment by ZPzhu** [comment]
非常感谢

**Comment by wangzhengchao** [comment]
@csbhr  感谢白博的贡献。 
我刚刚下载了项目。也是"Endpoint"的报错，导致跑不通。
1，这个应该是一个问题吧 ？ 
2，不知道现在有没有解决方案。

File "run_ms_api_attr.py", line 100, in <module>
    ms_api_attr = detect_face(image)
  File "run_ms_api_attr.py", line 55, in detect_face
    return_face_attributes=required_attr)
  File "/home/****/python3.7/site-packages/azure/cognitiveservices/vision/face/operations/_face_operations.py", line 778, in detect_with_stream
    request = self._client.post(url, query_parameters, header_parameters, body_content)
  File "/home/****/python3.7/site-packages/msrest/service_client.py", line 193, in post
    request = self._request('POST', url, params, headers, content, form_content)
  File "/home/****/python3.7/site-packages/msrest/service_client.py", line 108, in _request
    request = ClientRequest(method, self.format_url(url))
  File "/home/****/python3.7/site-packages/msrest/service_client.py", line 155, in format_url
    base = self.config.base_url.format(**kwargs).rstrip('/')
KeyError: 'Endpoint'

**Comment by csbhr** [comment]
@ZPzhu @wangzhengchao 

The project details of the FFHQ-UV dataset creation pipeline are available [[here]](https://github.com/csbhr/FFHQ-UV/blob/main/README_dataset.md#ffhq-uv-dataset-project-details), including inverted faces' latent codes (latents.zip) and detected face attributes of inverted faces (lights.zip, attributes.zip, attributes_ms_api.zip).

With these files, one can directly run step3 (DataSet_Step3_Editing) and step4 (DataSet_Step4_UV_Texture) to generate final texture UV-maps.

In "attributes_ms_api.zip", we provide the object returned by MS Face API, where one can find other detected attributes (e.g., age, gender, headPose, smile, facialHair, glasses, emotion, hair, makeup, occlusion, accessories, blur, exposure, noise, qualityForRecognition).

Since 380 samples failed in the [encoder4editing](https://github.com/omertov/encoder4editing) inversion task, we only provide information of the remaining 69620 samples.

**Comment by csbhr** [comment]
@Agent-INF 

这里有 .json 文件的示例：[https://github.com/csbhr/FFHQ-UV/tree/main/examples/dataset_examples/attributes](https://github.com/csbhr/FFHQ-UV/tree/main/examples/dataset_examples/attributes)

**Comment by ZPzhu** [comment]
Thanks very much!
