### ISSUE TITLE
about remove illumination of latent code generate dataset

### ISSUE THREAD

**Issue by 1406428260** [csbhr/FFHQ-UV#5]
Hi, I downloaded the one that generates the picture from latent code dataset，but there is still some light on the picture, is that normal
? 
Is this due to styleflow can not remove cleanly?
![image](https://user-images.githubusercontent.com/41857725/205905139-bb81e9fd-52a4-40bc-b225-eb979797e109.png)

**Comment by csbhr** [comment]
Yes, this is normal. Since StyleGAN's training data is realistic face images in complex lighting environments, it is not trivial for StyleFlow to obtain perfect de-illuminated faces. Most of the lighting and shadows are well removed, but some highlights remain in some samples.

This problem has been better alleviated in our released [FFHQ-UV-Interpolate](https://github.com/csbhr/FFHQ-UV#ffhq-uv-interpolate) dataset by using the latent space interpolation technique. 

This is one of the reasons we released this version of the dataset. Its diversity is compromised compared to FFHQ-UV dataset, but the quality has been well improved.

**Comment by 1406428260** [comment]
Thanks a lot
