### ISSUE TITLE
What is the KEY and ENDPOINT in ms_api?

### ISSUE THREAD

**Issue by miaoYuanyuan** [csbhr/FFHQ-UV#9]
how can i get a key and endpoint in ms_api?

**Comment by csbhr** [comment]
The project details of the FFHQ-UV dataset creation pipeline are available [[here]](https://github.com/csbhr/FFHQ-UV/blob/main/README_dataset.md#ffhq-uv-dataset-project-details), including inverted faces' latent codes (latents.zip) and detected face attributes of inverted faces (lights.zip, attributes.zip, attributes_ms_api.zip).

With these files, one can directly run step3 (DataSet_Step3_Editing) and step4 (DataSet_Step4_UV_Texture) to generate final texture UV-maps.

In "attributes_ms_api.zip", we provide the object returned by MS Face API, where one can find other detected attributes (e.g., age, gender, headPose, smile, facialHair, glasses, emotion, hair, makeup, occlusion, accessories, blur, exposure, noise, qualityForRecognition).

Since 380 samples failed in the [encoder4editing](https://github.com/omertov/encoder4editing) inversion task, we only provide information of the remaining 69620 samples.
